---
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: dark
locale: en-US
title: Minimal Mistakes Forestry Starter
title_separator: "-"
subtitle: 
name: Your Name
description: An amazing website.
url: 
baseurl: 
repository: 
teaser: 
logo: 
masthead_title: 
words_per_minute: "200"
comments:
  provider: 
  disqus:
    shortname: 
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
  utterances:
    theme: 
    issue_term: 
  staticman:
    branch: 
    endpoint: 
reCaptcha:
  siteKey: 
  secret: 
atom_feed:
  path: 
search: 
search_full_content: 
search_provider: 
algolia:
  application_id: 
  index_name: 
  search_only_api_key: 
  powered_by: 
google:
  search_engine_id: 
  instant_search: 
google_site_verification: 
bing_site_verification: 
yandex_site_verification: 
naver_site_verification: 
twitter:
  username: 
facebook:
  username: 
  app_id: 
  publisher: 
og_image: 
social:
  type: 
  name: 
  links: 
analytics:
  provider: false
  google:
    tracking_id: 
    anonymize_ip: 
author:
  name: Your Name
  avatar: 
  bio: I am an **amazing** person.
  location: Somewhere
  email: 
  links:
  - label: Email
    icon: fas fa-fw fa-envelope-square
  - label: Website
    icon: fas fa-fw fa-link
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
  - label: Facebook
    icon: fab fa-fw fa-facebook-square
  - label: GitHub
    icon: fab fa-fw fa-github
  - label: Instagram
    icon: fab fa-fw fa-instagram
footer:
  links:
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
  - label: Facebook
    icon: fab fa-fw fa-facebook-square
  - label: GitHub
    icon: fab fa-fw fa-github
  - label: GitLab
    icon: fab fa-fw fa-gitlab
  - label: Bitbucket
    icon: fab fa-fw fa-bitbucket
  - label: Instagram
    icon: fab fa-fw fa-instagram
include:
- ".htaccess"
- _pages
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- vendor
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- package-lock.json
- Rakefile
- README
- tmp
- "/docs"
- "/test"
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: "1"
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
paginate: "5"
paginate_path: "/page:num/"
timezone: 
plugins:
- jekyll-archives
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-include-cache
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development
collections:
  recipes:
    output: true
    permalink: "/:collection/:path/"
  pets:
    output: true
    permalink: "/:collection/:path/"
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: 
    share: true
    related: true
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: true
- scope:
    path: ''
    type: recipes
  values:
    layout: single
    author_profile: true
    share: true
    comments: true
- scope:
    path: ''
    type: pets
  values:
    layout: single
    author_profile: true
    share: true
    comment: true
